### PR TITLE
refactor: delete old firebase invites snippets

### PR DESCRIPTION
**Pull request by rosariopfernandes**
Correct me if I'm wrong, but I think these snippets are no longer shown in the Docs.

### CODE REVIEW

**Comment by samtstern** [comment]
@rosariopfernandes I think you're right about the `invites` module but I think the `dl-invites` ones (or at least some of them) are still used on this page: https://firebase.google.com/docs/dynamic-links/use-cases/user-to-user

**Comment by rosariopfernandes** [comment]
@samtstern Oops, that's true. I'll update this PR to keep `dl-invites`

**Comment by samtstern** [comment]
@rosariopfernandes :
```
FAILURE: Build failed with an exception.
> Configure project :test-lab:app

* What went wrong:
Project 'invites' not found in root project 'snippets-android'. Some candidates are: 'dl-invites'.
```

**Comment by rosariopfernandes** [comment]
@samtstern Seems like we just spotted a flaw on our modular build :laughing: 

The PR build is trying to build the `invites` module since it's the only one that contains changes and is not aware that it no longer exists :sweat_smile: :
```
Building Pull Request with
:invites:app:assembleDebug :invites:app:check
```

However, the [build succeeds](https://github.com/rosariopfernandes/snippets-android/runs/2148108964) if we build the whole project.

**Comment by samtstern** [comment]
@rosariopfernandes ah that makes sense!

**Pull request merged**
