### PR TITLE
feat : more idiomatic kotlin

### LINKED ISSUE #52: Dont mUse Hungarian notation in kotlin snippets
In reference to what @supercilex mentioned here, we should avoid hungarian notation in our Kotlin snippets.

https://twitter.com/SUPERCILEX/status/1050544888733818880?s=19

### PR DESCRIPTION
**Pull request by the-dagger**
Fix #52 
Signed-off-by: the-dagger <harshithdwivedi@gmail.com>

### CODE REVIEW

**Comment by samtstern** [comment]
@the-dagger nice!  What tools did you use for this?  Anything besides `ktlint`?

**Comment by the-dagger** [comment]
Mostly `ktlint`.
It was unable to fix a lot of warnings though, so I had to rely on the suggestions/warnings generated by Studio and fix them manually.

**Comment by samtstern** [comment]
LGTM!

By the way you can take a look at my quickstart-android PR:
https://github.com/firebase/quickstart-android/pull/699

It has a custom linter for hungarian notation (probably not necessary over here) and uses `ktlint` as part of the build.

**Comment by the-dagger** [comment]
@samtstern should we add ktlint and the lint checks from `quickstart-android` over here in the `snnippets`?

**Comment by samtstern** [comment]
@the-dagger added the lint in:
https://github.com/firebase/snippets-android/pull/54

**Pull request merged**
