### PR TITLE
WIP Change Firestore samples to use KTX and coroutines.

### PR DESCRIPTION
**Pull request by vkryachko**

### CODE REVIEW

**Comment by samtstern** [comment]
@vkryachko thanks for this!  This looks mostly good but is premature, these snippets are automatically pulled into docs from `master` so we need to finish all the docs that force Kotlin users to use KTX before we can make the snippet changes.

Also I am happy to make the rest of the updates to the Kotlin snippets (and actually would prefer to do it as a learning experience).

**Comment by vkryachko** [comment]
@samtstern cool, sg. I just made these as an exercise as well, definitely too early to merge

**Review by willmastered — APPROVED** [review]
firestore/app/build.gradle

**Comment by samtstern** [comment]
@vkryachko closing this one since it's pretty old and we have KTX snippets now (but no coroutines!)

**Pull request closed without merging**
