### PR TITLE
feat(auth): move snippets from quickstart-android

### PR DESCRIPTION
**Pull request by rosariopfernandes**
As part of firebase/quickstart-android#1217, this should move the auth snippets from the quickstart repo to this one.

All snippet names remain the same, and the file names are also the same.

### CODE REVIEW

**Comment by samtstern** [comment]
@rosariopfernandes whaaaaaaat! You are such a legend, thank you for doing this!

**Comment by samtstern** [comment]
I'm going to merge this and then make the docs updates, will let you know if anything seems missing (if I can't fix it myself)

**Comment by rosariopfernandes** [comment]
Sure @samtstern :)

I'm working on a PR to remove these snippets from the quickstart repo, I'll send it once I migrate the auth quickstart to the Jetpack Navigation Component.

**Comment by samtstern** [comment]
@rosariopfernandes took me a little bit but got all the internal docs updated, you didn't miss any snippets!

**Pull request merged**
