### PR TITLE
feat : kotlinize indexing snippets

### PR DESCRIPTION
**Pull request by the-dagger**
@samtstern I seem to have missed out on the appindexing module in the earlier PR, sorry about that!

### CODE REVIEW

**Comment by the-dagger** [comment]
@samtstern the project build well on my local machine but on travis it fails with an error message similar to the one in #40.
Could you check to see if it works well for you?

**Comment by samtstern** [comment]
I am seeing this on my local machine:

```
The library com.google.firebase:firebase-iid is being requested by various other libraries at [[17.0.0,17.0.0]], but resolves to 16.0.0. Disable the plugin and check your dependencies tree using ./gradlew :app:dependencies.
```

I'll try to find a fix.

**Comment by samtstern** [comment]
I was able to fix the build with this diff:

```
$ git diff --cached 
diff --git a/instanceid/app/build.gradle b/instanceid/app/build.gradle
index f5f373a..3d3bbef 100644
--- a/instanceid/app/build.gradle
+++ b/instanceid/app/build.gradle
@@ -23,6 +23,6 @@ android {
 dependencies {
     implementation "com.android.support:support-v4:27.1.1"
     implementation "com.android.support:appcompat-v7:27.1.1"
-    implementation "com.google.firebase:firebase-iid:17.0.0"
+    implementation "com.google.firebase:firebase-iid:17.0.1"
     implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
 }
diff --git a/messaging/app/build.gradle b/messaging/app/build.gradle
index 6701946..fc4a4e1 100644
--- a/messaging/app/build.gradle
+++ b/messaging/app/build.gradle
@@ -23,7 +23,7 @@ android {
 dependencies {
     implementation "com.android.support:support-v4:27.1.1"
     implementation "com.android.support:appcompat-v7:27.1.1"
-    implementation "com.google.firebase:firebase-messaging:17.3.0"
+    implementation "com.google.firebase:firebase-messaging:17.3.1"
     implementation "com.google.android.gms:play-services-auth:16.0.0"
     implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
 }
diff --git a/test-lab/app/build.gradle b/test-lab/app/build.gradle
index d05e2c6..6b9cf5c 100644
--- a/test-lab/app/build.gradle
+++ b/test-lab/app/build.gradle
@@ -29,7 +29,7 @@ repositories {
 dependencies {
     implementation "com.android.support:support-v4:27.1.1"
     implementation "com.android.support:appcompat-v7:27.1.1"
-    implementation "com.google.firebase:firebase-iid:17.0.0"
+    implementation "com.google.firebase:firebase-iid:17.0.1"
     implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
 
     implementation(name:'cloudtestingscreenshotter_lib', ext:'aar')
```

I will send a PR to `master`

**Comment by samtstern** [comment]
@the-dagger confirmed that our build is flaky so gonna merge this over the objections.

Remember: we are humans and machines can't tell us what to do!

**Comment by the-dagger** [comment]
Thanks!

**Pull request merged**
